aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_BDR1-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.48/31
  peer: BDR1-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_BDR2-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.52/31
  peer: BDR2-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet3
  description: P2P_SVC1-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.56/31
  peer: SVC1-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet4
  description: P2P_SVC2-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.60/31
  peer: SVC2-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet5
  description: P2P_DLF1-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.64/31
  peer: DLF1-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet6
  description: P2P_DLF2-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.68/31
  peer: DLF2-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet7
  description: P2P_DLF3-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.72/31
  peer: DLF3-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet8
  description: P2P_DLF4-FAB2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 198.18.251.76/31
  peer: DLF4-FAB2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
hostname: SPN1-FAB2
ip_routing: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$TCSACrtM5.u0huKw$J404.NgN8rxlGc67pTcJEUUWdDyQAm9fZSbEllRpjPOfIcoODqy0KqY0Njs/2ceM.486UhzTzRA0t4QuapAYP/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$.icFWOMuXv.9RiWQ$g0FtXFBSjP2A6AH6lIPA44rLkklmJqdrSwW3IMhM2DgJyWYFe/06ILKBYpUt0VcGSyA8VJudujxNVWGG75wB/.
- name: gregg
  privilege: 15
  role: network-admin
  no_password: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 198.18.250.235/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.160/24
  type: oob
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: FABRIC
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 198.18.250.224/27 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65200'
  router_id: 198.18.250.235
  maximum_paths:
    paths: 4
    ecmp: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: 7x4B4rnJhZB438m9+BrBfQ==
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 198.18.251.49
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65201'
    peer: BDR1-FAB2
    description: BDR1-FAB2_Ethernet1
  - ip_address: 198.18.251.53
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65201'
    peer: BDR2-FAB2
    description: BDR2-FAB2_Ethernet1
  - ip_address: 198.18.251.57
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65202'
    peer: SVC1-FAB2
    description: SVC1-FAB2_Ethernet1
  - ip_address: 198.18.251.61
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65202'
    peer: SVC2-FAB2
    description: SVC2-FAB2_Ethernet1
  - ip_address: 198.18.251.65
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65203'
    peer: DLF1-FAB2
    description: DLF1-FAB2_Ethernet1
  - ip_address: 198.18.251.69
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65203'
    peer: DLF2-FAB2
    description: DLF2-FAB2_Ethernet1
  - ip_address: 198.18.251.73
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65204'
    peer: DLF3-FAB2
    description: DLF3-FAB2_Ethernet1
  - ip_address: 198.18.251.77
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65204'
    peer: DLF4-FAB2
    description: DLF4-FAB2_Ethernet1
  - ip_address: 198.18.250.79
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65201'
    peer: BDR1-FAB2
    description: BDR1-FAB2_Loopback0
  - ip_address: 198.18.250.80
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65201'
    peer: BDR2-FAB2
    description: BDR2-FAB2_Loopback0
  - ip_address: 198.18.250.83
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65203'
    peer: DLF1-FAB2
    description: DLF1-FAB2_Loopback0
  - ip_address: 198.18.250.84
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65203'
    peer: DLF2-FAB2
    description: DLF2-FAB2_Loopback0
  - ip_address: 198.18.250.85
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65204'
    peer: DLF3-FAB2
    description: DLF3-FAB2_Loopback0
  - ip_address: 198.18.250.86
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65204'
    peer: DLF4-FAB2
    description: DLF4-FAB2_Loopback0
  - ip_address: 198.18.250.81
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65202'
    peer: SVC1-FAB2
    description: SVC1-FAB2_Loopback0
  - ip_address: 198.18.250.82
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65202'
    peer: SVC2-FAB2
    description: SVC2-FAB2_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
